"""Added required tables 4

Revision ID: 623bb6f7b113
Revises: 
Create Date: 2022-11-03 13:58:10.342780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '623bb6f7b113'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('indicators_access', 'indicator_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('indicators_access', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('indicators_access', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('indicators_access', 'indicator_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
